sudo: true

dist: trusty

language: php

php:
  - nightly
  - 7.3
  - 7.2
  - 7.1

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer install --no-interaction
  - sudo locale-gen uk_UA.UTF-8

script:
  - mkdir -p build/logs
  - composer cover

after_script:
  - composer coveralls
