language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3

before_script:
  - composer install --dev --no-interaction
  - locale-gen uk_UA.UTF-8
  
script:
  - mkdir -p build/logs
  - phpunit --bootstrap ./tests/bootstrap.php -c tests/phpunit.xml --coverage-clover build/logs/clover.xml tests
  
after_script:
  - php ./vendor/bin/coveralls -v
