sudo: false

dist: trusty

language: php

php:
  - nightly
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

matrix:
  allow_failures:
    - php: nightly
  include:
    - php: "5.3"
      dist: precise

before_script:
  - composer install --dev --no-interaction
  - sudo locale-gen uk_UA.UTF-8
  
script:
  - mkdir -p build/logs
  - composer cover
  
after_script:
  - composer coveralls
